movie/urls.py
from django.urls import path
from . import views

app_name = "movies"

urlpatterns = [
    path('',views.list, name="list"),
    path('create/', views.create, name="create"),
    path('<int:id>/', views.detail, name="detail"),
    path('form_create/', views.form_create, name="form_create"),
    path('model_form_create/', views.model_form_create, name="model_form_create"),
    path('<int:id>/form_update/', views.form_update, name="form_update"),
    path("<int:id>/model_form_update",views.model_form_update,name="model_form_update")
    
    ]

watcha/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include("movie.urls")),
]

movie/models.py
from django.db import models

# Create your models here.

class Movie(models.Model):
    title = models.CharField(max_length=100)
    title_en = models.CharField(max_length=100)
    audience = models.IntegerField()
    open_date = models.DateField()
    genre = models.CharField(max_length=100)
    watch_grade = models.CharField(max_length=100)
    score = models.FloatField()
    poster_url = models.TextField()
    description = models.TextField()
    
    def __str__(self):
        return self.title
        

movie/forms.py
from django import forms
from .models import Movie
class MovieForm(forms.Form):
    title = forms.CharField(max_length=100)
    title_en = forms.CharField(max_length=100)
    audience = forms.IntegerField()
    open_date = forms.DateField(
        widget = forms.widgets.DateInput(attrs={'type':'date'})
        )
    genre = forms.CharField(max_length=100)
    watch_grade = forms.CharField(max_length=100)
    score = forms.FloatField()
    poster_url = forms.CharField()
    description = forms.CharField(widget=forms.Textarea())
    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
class MovieModelForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'
        widgets = {
            'open_date': forms.DateInput(attrs={'type':'date'})
        }
    
        
    
    
    

movie/views.py
from django.shortcuts import render, redirect
from .models import Movie
from .forms import MovieForm, MovieModelForm
# Create your views here.
def list(request):
    movies = Movie.objects.all()
    return render(request, "movie/list.html", {'movies':movies})

def create(request):
    if request.method == "POST":
        title = request.POST.get("title")
        title_en = request.POST.get("title_en")
        audience = request.POST.get("audience")
        open_date = request.POST.get("open_date")
        genre = request.POST.get("genre")
        watch_grade = request.POST.get("watch_grade")
        score = request.POST.get("score")
        poster_url = request.POST.get("poster_url")
        description = request.POST.get("description")
        
        Movie.objects.create(title=title,title_en=title_en,audience=audience,open_date=open_date,
        genre=genre,watch_grade=watch_grade,score=score,poster_url=poster_url,
        description=description)
        return redirect("movies:list")
    else:
        return render(request, "movie/create.html")
        
def detail(request, id):
    movie = Movie.objects.get(pk=id)
    return render(request,"movie/detail.html",{'movie':movie})
    
def form_create(request):
    if request.method == "POST":
        form = MovieForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get("title")
            title_en = form.cleaned_data.get("title_en")
            audience = form.cleaned_data.get("audience")
            open_date = form.cleaned_data.get("open_date")
            genre = form.cleaned_data.get("genre")
            watch_grade = form.cleaned_data.get("watch_grade")
            score = form.cleaned_data.get("score")
            poster_url = form.cleaned_data.get("poster_url")
            description = form.cleaned_data.get("description")
            
            Movie.objects.create(title=title,title_en=title_en,audience=audience,open_date=open_date,
            genre=genre,watch_grade=watch_grade,score=score,poster_url=poster_url,
            description=description)
            return redirect('movies:list')
    else:
        form = MovieForm()
    return render(request,"movie/form_create.html",{'form':form})
    
def form_update(request, id):
    movie = Movie.objects.get(id=id)
    if request.method == "POST":
        form = MovieForm(request.POST)
        if form.is_valid():
            movie.title = form.cleaned_data.get("title")
            movie.title_en = form.cleaned_data.get("title_en")
            movie.audience = form.cleaned_data.get("audience")
            movie.open_date = form.cleaned_data.get("open_date")
            movie.genre = form.cleaned_data.get("genre")
            movie.watch_grade = form.cleaned_data.get("watch_grade")
            movie.score = form.cleaned_data.get("score")
            movie.poster_url = form.cleaned_data.get("poster_url")
            movie.description = form.cleaned_data.get("description")
            movie.save()
            
            return redirect('movies:list')
            
        
    else:
        data = {
            "title":movie.title,
            "title_en":movie.title_en,
            "audience":movie.audience,
            "open_date":movie.open_date,
            "genre":movie.genre,
            "watch_grade":movie.watch_grade,
            "score":movie.score,
            "poster_url":movie.poster_url,
            "description":movie.description
        }
        form = MovieForm(data)
        return render(request,"movie/form_update.html",{'form':form})
        
def model_form_create(request):
    if request.method == "POST":
        form = MovieModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("movies:list")
    else:
        form = MovieModelForm()
    return render(request,"movie/model_form_create.html",{'form':form})
    
def model_form_update(request,id):
    movie = Movie.objects.get(id=id)
    if request.method == "POST":
        form = MovieModelForm(request.POST, instance=movie)
        if form.is_valid():
            form.save()
            return redirect("movies:detail", id)
    else:
        form = MovieModelForm(instance=movie)
    return render(request,"movie/model_form_update.html",{'form':form})
    







    
    
    

movie/templates/movie/base.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    {% bootstrap_css %}
</head>
<body>
    <a href="{% url 'movies:list' %}">인덱스</a>
    <a href="{% url 'movies:create' %}">글작성</a>
    <a href="{% url 'movies:form_create' %}">폼으로글작성</a>
    <a href="{% url 'movies:model_form_create' %}"> 모델폼으로글작성</a>
    
    <div class="container">
        
        {%block bb%}
        {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
</body>
</html>

movie/templates/movie/create.html
{% extends 'movie/base.html' %}
{% block bb %}
    <form method="post">
        {% csrf_token %}
      <div class="form-group">
        <label for="title">영화제목</label>
        <input type="text" class="form-control" id="title" name="title" required/>
      </div>
      <div class="form-group">
        <label for="title_en">영문제목</label>
        <input type="text" class="form-control" id="title_en" name="title_en" required/>
      </div>
      <div class="form-group">
        <label for="audience">관객</label>
        <input type="number" class="form-control" id="audience" name="audience">
      </div>
      <div class="form-group">
        <label for="open_date">개봉일</label>
        <input type="date" class="form-control" id="open_date" name="open_date">
      </div>
      <div class="form-group">
        <label for="genre">장르</label>
        <input type="text" class="form-control" id="genre" name="genre">
      </div>
      <div class="form-group">
        <label for="watch_grade">관람등급</label>
        <input type="text" class="form-control" id="watch_grade" name="watch_grade">
      </div>
      <div class="form-group">
        <label for="score">평점</label>
        <input type="number" step="0.01" class="form-control" id="score" name="score">
      </div>
      <div class="form-group">
        <label for="poster_url">포스터 보기</label>
        <input type="text" class="form-control" id="poster_url" name="poster_url">
      </div>
      <div class="form-group">
        <label for="description">상세설명</label>
        <textarea rows="4" cols="50" name="description"></textarea>
      </div>
      
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
{% endblock %}

movie/templates/movie/detail.html
{% extends 'movie/base.html' %}
{% block bb %}
    <h1>{{movie.title}}</h1>
    <h1>{{movie.title_en}}</h1>
    <h1>{{movie.audience}}</h1>
    <h1>{{movie.open_date}}</h1>
    <h1>{{movie.genre}}</h1>
    <h1>{{movie.watch_grade}}</h1>
    <h1>{{movie.score}}</h1>
    <h1>{{movie.poster_url}}</h1>
    <h1>{{movie.description}}</h1>
    <a href="{% url 'movies:form_update' movie.id%}">폼으로수정하기</a>
    <a href="{% url 'movies:model_form_update' movie.id%}">모델 폼으로수정하기</a>
{% endblock %}

movie/templates/movie/form_create.html
{% extends 'movie/base.html' %}
{% load bootstrap4 %}
{% block bb %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="submit">
    </form>
{% endblock %}

movie/templates/movie/form_update.html
{% extends 'movie/base.html' %}
{% load bootstrap4 %}
{% block bb %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="submit">
    </form>
{% endblock %}

movie/templates/movie/list.html
{% extends 'movie/base.html' %}
{% block bb %}
    {% for movie in movies %}
        <h1>{{movie.title}}</h1>
        <a href="{% url 'movies:detail' movie.id %}">글보기</a>
    {% endfor %}
{% endblock %}

movie/templates/movie/model_form_create.1.html
{% extends 'movie/base.html' %}
{% load bootstrap4 %}
{% block bb %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="submit">
    </form>
{% endblock %}

movie/templates/movie/model_form_update.html
{% extends 'movie/base.html' %}
{% load bootstrap4 %}
{% block bb %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="submit">
    </form>
{% endblock %}